Task 1: Handling missing values

Task 2: Scaling and normalization

Task 3: Parsing dates

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

#### Parsing Dates

In [2]:
data = pd.read_csv("Building_Permits.csv")
data.head()

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  object
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  object
 3   Permit Creation Date                    198900 non-null  object
 4   Block                                   198900 non-null  object
 5   Lot                                     198900 non-null  object
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    object
 8   Street Name                             198900 non-null  object
 9   Street Suffix                           196132 non-null  object
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    object
 12  Description                             198610 non-null  object
 13  Current Status                          198900 non-null  object
 14  Current Status Date                     198900 non-null  object
 15  Filed Date                              198900 non-null  object
 16  Issued Date                             183960 non-null  object
 17  Completed Date                          97191 non-null   object
 18  First Construction Document Date        183954 non-null  object
 19  Structural Notification                 6922 non-null    object
 20  Number of Existing Stories              156116 non-null  float64
 21  Number of Proposed Stories              156032 non-null  float64
 22  Voluntary Soft-Story Retrofit           35 non-null      object
 23  Fire Only Permit                        18827 non-null   object
 24  Permit Expiration Date                  147020 non-null  object
 25  Estimated Cost                          160834 non-null  float64
 26  Revised Cost                            192834 non-null  float64
 27  Existing Use                            157786 non-null  object
 28  Existing Units                          147362 non-null  float64
 29  Proposed Use                            156461 non-null  object
 30  Proposed Units                          147989 non-null  float64
 31  Plansets                                161591 non-null  float64
 32  TIDF Compliance                         2 non-null       object
 33  Existing Construction Type              155534 non-null  float64
 34  Existing Construction Type Description  155534 non-null  object
 35  Proposed Construction Type              155738 non-null  float64
 36  Proposed Construction Type Description  155738 non-null  object
 37  Site Permit                             5359 non-null    object
 38  Supervisor District                     197183 non-null  float64
 39  Neighborhoods - Analysis Boundaries     197175 non-null  object
 40  Zipcode                                 197184 non-null  float64
 41  Location                                197200 non-null  object
 42  Record ID                               198900 non-null  int64
dtypes: float64(12), int64(3), object(28)
memory usage: 65.3+ MB

In [4]:
data = pd.read_csv("Building_Permits.csv", parse_dates = ["Permit Creation Date", "Current Status Date", "Filed Date", "Issued Date", "Completed Date", "First Construction Document Date"])
data.head()

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,2015-05-06,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,2016-04-19,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,2016-05-27,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,2016-11-07,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,2016-11-28,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  object
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  object
 3   Permit Creation Date                    198900 non-null  datetime64[ns]
 4   Block                                   198900 non-null  object
 5   Lot                                     198900 non-null  object
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    object
 8   Street Name                             198900 non-null  object
 9   Street Suffix                           196132 non-null  object
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    object
 12  Description                             198610 non-null  object
 13  Current Status                          198900 non-null  object
 14  Current Status Date                     198900 non-null  datetime64[ns]
 15  Filed Date                              198900 non-null  datetime64[ns]
 16  Issued Date                             183960 non-null  datetime64[ns]
 17  Completed Date                          97191 non-null   datetime64[ns]
 18  First Construction Document Date        183954 non-null  datetime64[ns]
 19  Structural Notification                 6922 non-null    object
 20  Number of Existing Stories              156116 non-null  float64
 21  Number of Proposed Stories              156032 non-null  float64
 22  Voluntary Soft-Story Retrofit           35 non-null      object
 23  Fire Only Permit                        18827 non-null   object
 24  Permit Expiration Date                  147020 non-null  object
 25  Estimated Cost                          160834 non-null  float64
 26  Revised Cost                            192834 non-null  float64
 27  Existing Use                            157786 non-null  object
 28  Existing Units                          147362 non-null  float64
 29  Proposed Use                            156461 non-null  object
 30  Proposed Units                          147989 non-null  float64
 31  Plansets                                161591 non-null  float64
 32  TIDF Compliance                         2 non-null       object
 33  Existing Construction Type              155534 non-null  float64
 34  Existing Construction Type Description  155534 non-null  object
 35  Proposed Construction Type              155738 non-null  float64
 36  Proposed Construction Type Description  155738 non-null  object
 37  Site Permit                             5359 non-null    object
 38  Supervisor District                     197183 non-null  float64
 39  Neighborhoods - Analysis Boundaries     197175 non-null  object
 40  Zipcode                                 197184 non-null  float64
 41  Location                                197200 non-null  object
 42  Record ID                               198900 non-null  int64
dtypes: datetime64[ns](6), float64(12), int64(3), object(22)
memory usage: 65.3+ MB

#### Missing Values Check

In [6]:
data.isna().sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [7]:
data["Street Number Suffix"] = data["Street Number Suffix"].fillna("U")

data["Street Suffix"] = data["Street Suffix"].fillna("U")

data["Unit"] = data["Unit"].fillna(data["Unit"].mean())

data["Unit Suffix"] = data["Unit Suffix"].fillna("U")

data["Description"] = data["Description"].fillna("U")

data["Issued Date"] = data["Issued Date"].fillna("U")

data["Completed Date"] = data["Completed Date"].fillna("U")

data["First Construction Document Date"] = data["First Construction Document Date"].fillna("U")

data["Structural Notification"] = data["Structural Notification"].fillna("U")

data["Number of Existing Stories"] = data["Number of Existing Stories"].fillna(data["Number of Existing Stories"].mean())

data["Number of Proposed Stories"] = data["Number of Proposed Stories"].fillna(data["Number of Proposed Stories"].mean())

data["Voluntary Soft-Story Retrofit"] = data["Voluntary Soft-Story Retrofit"].fillna("U")

data["Fire Only Permit"] = data["Fire Only Permit"].fillna("U")

data["Permit Expiration Date"] = data["Permit Expiration Date"].fillna("U")

data["Estimated Cost"] = data["Estimated Cost"].fillna(data["Estimated Cost"].mean())

data["Revised Cost"] = data["Revised Cost"].fillna(data["Revised Cost"].mean())

data["Existing Use"] = data["Existing Use"].fillna("U")

data["Existing Units"] = data["Existing Units"].fillna(data["Existing Units"].mean())

data["Proposed Use"] = data["Proposed Use"].fillna("U")

data["Proposed Units"] = data["Proposed Units"].fillna(data["Proposed Units"].mean())

data["Plansets"] = data["Plansets"].fillna(data["Plansets"].mean())

data["TIDF Compliance"] = data["TIDF Compliance"].fillna("U")

#data[""] = data[""].fillna(data[""].mean())

data["Existing Construction Type"] = data["Existing Construction Type"].fillna(data["Existing Construction Type"].mean())

data["Existing Construction Type Description"] = data["Existing Construction Type Description"].fillna("U")

data["Proposed Construction Type"] = data["Proposed Construction Type"].fillna(data["Proposed Construction Type"].mean())

data["Proposed Construction Type Description"] = data["Proposed Construction Type Description"].fillna("U")

data["Site Permit"] = data["Site Permit"].fillna("U")

data["Supervisor District"] = data["Supervisor District"].fillna(data["Supervisor District"].mean())

data["Neighborhoods - Analysis Boundaries"] = data["Neighborhoods - Analysis Boundaries"].fillna("U")

data["Zipcode"] = data["Zipcode"].fillna("U")

data["Location"] = data["Location"].fillna("U")

#data[""] = data[""].fillna(data[""].mean())

In [8]:
data.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,2015-05-06,0326,023,140,U,Ellis,St,...,3.0,constr type 3,4.089529,U,U,3.0,Tenderloin,94102,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,2016-04-19,0306,007,440,U,Geary,St,...,3.0,constr type 3,4.089529,U,U,3.0,Tenderloin,94102,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,2016-05-27,0595,203,1647,U,Pacific,Av,...,1.0,constr type 1,1.000000,constr type 1,U,3.0,Russian Hill,94109,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,2016-11-07,0156,011,1230,U,Pacific,Av,...,5.0,wood frame (5),5.000000,wood frame (5),U,3.0,Nob Hill,94109,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,2016-11-28,0342,001,950,U,Market,St,...,3.0,constr type 3,4.089529,U,U,6.0,Tenderloin,94102,"(37.78315261897309, -122.40950883997789)",144548169992

In [9]:
data.isna().sum()

Permit Number                             0
Permit Type                               0
Permit Type Definition                    0
Permit Creation Date                      0
Block                                     0
Lot                                       0
Street Number                             0
Street Number Suffix                      0
Street Name                               0
Street Suffix                             0
Unit                                      0
Unit Suffix                               0
Description                               0
Current Status                            0
Current Status Date                       0
Filed Date                                0
Issued Date                               0
Completed Date                            0
First Construction Document Date          0
Structural Notification                   0
Number of Existing Stories                0
Number of Proposed Stories                0
Voluntary Soft-Story Retrofit             0
Fire Only Permit                          0
Permit Expiration Date                    0
Estimated Cost                            0
Revised Cost                              0
Existing Use                              0
Existing Units                            0
Proposed Use                              0
Proposed Units                            0
Plansets                                  0
TIDF Compliance                           0
Existing Construction Type                0
Existing Construction Type Description    0
Proposed Construction Type                0
Proposed Construction Type Description    0
Site Permit                               0
Supervisor District                       0
Neighborhoods - Analysis Boundaries       0
Zipcode                                   0
Location                                  0
Record ID                                 0
dtype: int64

In [10]:
data.shape

(198900, 43)

In [11]:
#data = data.dropna()

#data.isna().sum()

In [12]:
data.shape

(198900, 43)

#### Scaling And Normalisation

In [13]:
data.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,2015-05-06,0326,023,140,U,Ellis,St,...,3.0,constr type 3,4.089529,U,U,3.0,Tenderloin,94102,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,2016-04-19,0306,007,440,U,Geary,St,...,3.0,constr type 3,4.089529,U,U,3.0,Tenderloin,94102,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,2016-05-27,0595,203,1647,U,Pacific,Av,...,1.0,constr type 1,1.000000,constr type 1,U,3.0,Russian Hill,94109,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,2016-11-07,0156,011,1230,U,Pacific,Av,...,5.0,wood frame (5),5.000000,wood frame (5),U,3.0,Nob Hill,94109,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,2016-11-28,0342,001,950,U,Market,St,...,3.0,constr type 3,4.089529,U,U,6.0,Tenderloin,94102,"(37.78315261897309, -122.40950883997789)",144548169992

In [18]:
df_num = data[['Unit','Number of Existing Stories', 'Number of Proposed Stories',
       'Estimated Cost', 'Revised Cost', 'Existing Units', 'Proposed Units',
       'Plansets', 'Existing Construction Type', 'Proposed Construction Type',
       'Supervisor District']]
df_num.head()

,Unit,Number of Existing Stories,Number of Proposed Stories,Estimated Cost,Revised Cost,Existing Units,Proposed Units,Plansets,Existing Construction Type,Proposed Construction Type,Supervisor District
0,78.517182,6.0,5.745043,4000.0,4000.000000,143.000000,16.51095,2.0,3.0,4.089529,3.0
1,0.000000,7.0,5.745043,1.0,500.000000,15.666164,16.51095,2.0,3.0,4.089529,3.0
2,78.517182,6.0,6.000000,20000.0,132856.186492,39.000000,39.00000,2.0,1.0,1.000000,3.0
3,0.000000,2.0,2.000000,2000.0,2000.000000,1.000000,1.00000,2.0,5.0,5.000000,3.0
4,78.517182,3.0,5.745043,100000.0,100000.000000,15.666164,16.51095,2.0,3.0,4.089529,6.0

In [19]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on  data
norm = MinMaxScaler()

norm.fit(df_num)

# transform data
data_norm = norm.transform(df_num)

In [20]:
data_norm = pd.DataFrame(data_norm)
data_norm.head()

,0,1,2,3,4,5,6,7,8,9,10
0,0.013077,0.076923,0.073654,0.000007,5.124920e-06,0.074987,0.008640,0.000222,0.5,0.772382,0.2
1,0.000000,0.089744,0.073654,0.000000,6.406150e-07,0.008215,0.008640,0.000222,0.5,0.772382,0.2
2,0.013077,0.076923,0.076923,0.000037,1.702193e-04,0.020451,0.020408,0.000222,0.0,0.000000,0.2
3,0.000000,0.025641,0.025641,0.000004,2.562460e-06,0.000524,0.000523,0.000222,1.0,1.000000,0.2
4,0.013077,0.038462,0.073654,0.000186,1.281230e-04,0.008215,0.008640,0.000222,0.5,0.772382,0.5

In [21]:
# data normalization with sklearn
from sklearn.preprocessing import StandardScaler

# fit scaler on  data
ss = StandardScaler()
ss.fit(df_num)

# transform data
data_ss = ss.transform(df_num)

In [23]:
data_ss = pd.DataFrame(data_ss)
data_ss.head()

,0,1,2,3,4,5,6,7,8,9,10
0,-2.257853e-16,0.038557,1.164242e-16,-0.050529,-0.036505,1.986331,0.000000,0.035914,-0.765103,0.000000,-0.883063
1,-6.237494e-01,0.169601,1.164242e-16,-0.051754,-0.037497,0.000000,0.000000,0.035914,-0.765103,0.000000,-0.883063
2,-2.257853e-16,0.038557,3.342033e-02,-0.045628,0.000000,0.363994,0.346609,0.035914,-2.191366,-2.211546,-0.883063
3,-6.237494e-01,-0.485620,-4.909078e-01,-0.051142,-0.037072,-0.228783,-0.239060,0.035914,0.661160,0.651734,-0.883063
4,-2.257853e-16,-0.354576,1.164242e-16,-0.021123,-0.009308,0.000000,0.000000,0.035914,-0.765103,0.000000,0.160581